version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: react_wagtail_app_web
    command: /start
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env/.dev-sample
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=react_wagtail_dev
      - POSTGRES_USER=react_wagtail
      - POSTGRES_PASSWORD=react_wagtail

  frontend:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: react_wagtail_app_frontend
    command: yarn start
    volumes:
      - .:/app
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/frontend/node_modules
    ports:
      - 3000:3000
    depends_on:
      - web
    stdin_open: true

  storybook:
    build:
      context: .
      dockerfile: ./compose/local/node/Dockerfile
    image: react_wagtail_app_storybook
    command: yarn storybook
    volumes:
      - .:/app
      # http://jdlm.info/articles/2016/03/06/lessons-building-node-app-docker.html
      - /app/frontend/node_modules
    ports:
      - 6006:6006
    depends_on:
      - web
    stdin_open: true


volumes:
  postgres_data:
