# Generated by Django 3.2 on 2021-09-02 04:01

import blog.blocks
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='body',
            field=wagtail.core.fields.StreamField([('h1', wagtail.core.blocks.CharBlock()), ('h2', wagtail.core.blocks.CharBlock()), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image_text', wagtail.core.blocks.StructBlock([('reverse', wagtail.core.blocks.BooleanBlock(required=False)), ('text', wagtail.core.blocks.RichTextBlock()), ('image', blog.blocks.CustomImageChooserBlock())])), ('image_carousel', wagtail.core.blocks.ListBlock(blog.blocks.CustomImageChooserBlock())), ('thumbnail_gallery', wagtail.core.blocks.ListBlock(blog.blocks.CustomImageChooserBlock()))], blank=True),
        ),
    ]
